# Generated by Django 5.1.6 on 2025-02-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="account",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
